using System.Diagnostics;
using System.IO;
using System.Net;
using System.Text;
using Microsoft.Win32;

namespace ExportX.Services;

public static class AuthService
{
    private static CancellationTokenSource? _activeAuthCts;
    private static HttpListener? _httpListener;

    public static string DetectDefaultBrowser()
    {
        try
        {
            using var key = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice");
            var progId = key?.GetValue("ProgId")?.ToString() ?? "";
            if (progId.Contains("Brave", StringComparison.OrdinalIgnoreCase)) return "brave";
            if (progId.Contains("Firefox", StringComparison.OrdinalIgnoreCase)) return "firefox";
            if (progId.Contains("Chrome", StringComparison.OrdinalIgnoreCase)) return "chrome";
            if (progId.Contains("Edge", StringComparison.OrdinalIgnoreCase)) return "edge";
            if (progId.Contains("Opera", StringComparison.OrdinalIgnoreCase)) return "opera";
            if (progId.Contains("Vivaldi", StringComparison.OrdinalIgnoreCase)) return "vivaldi";
        }
        catch { }
        return "brave";
    }

    public static void CancelOngoingAuth()
    {
        try
        {
            _activeAuthCts?.Cancel();
            _activeAuthCts = null;
        }
        catch { }

        try
        {
            if (_httpListener != null && _httpListener.IsListening)
            {
                _httpListener.Stop();
                _httpListener.Close();
            }
            _httpListener = null;
        }
        catch { }
    }

    public static async Task<bool> StartBrowserLoginFlowAsync(Action<string> onStatusUpdate, TimeSpan? timeout = null)
    {
        CancelOngoingAuth();
        _activeAuthCts = new CancellationTokenSource();
        var token = _activeAuthCts.Token;

        var targetCookiesPath = ConfigService.GetCookiesPath();
        var dir = Path.GetDirectoryName(targetCookiesPath);
        if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
        {
            Directory.CreateDirectory(dir);
        }

        int port = 58432;
        string callbackPrefix = $"http://127.0.0.1:{port}/";

        try
        {
            _httpListener = new HttpListener();
            _httpListener.Prefixes.Add(callbackPrefix);
            _httpListener.Start();
        }
        catch
        {
            port = 58433;
            callbackPrefix = $"http://127.0.0.1:{port}/";
            try
            {
                _httpListener = new HttpListener();
                _httpListener.Prefixes.Add(callbackPrefix);
                _httpListener.Start();
            }
            catch (Exception ex)
            {
                LogService.Warn($"Nie udało się uruchomić serwera HTTP: {ex.Message}", "AUTH");
            }
        }

        // Native Google OAuth Account Chooser URL
        string clientId = "1071006060591-tmhssin2h21lcre235vtolojh4q403ep.apps.googleusercontent.com";
        string redirectUri = $"http://127.0.0.1:{port}/callback";
        string googleOAuthUrl = $"https://accounts.google.com/o/oauth2/v2/auth?client_id={clientId}&redirect_uri={Uri.EscapeDataString(redirectUri)}&response_type=code&scope=openid%20profile%20email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fyoutube.readonly&access_type=offline&prompt=select_account";

        try
        {
            Process.Start(new ProcessStartInfo(googleOAuthUrl) { UseShellExecute = true });
            LogService.Info("Otwarto oficjalną stronę wyboru konta Google w domyślnej przeglądarce.", "AUTH");
        }
        catch (Exception ex)
        {
            LogService.Warn($"Nie udało się otworzyć przeglądarki: {ex.Message}", "AUTH");
        }

        onStatusUpdate("Otwarto wybór konta Google w przeglądarce. Kliknij swoje konto...");

        var tcs = new TaskCompletionSource<bool>();

        // Fast HTTP Server - Immediately catches the OAuth callback from Google
        if (_httpListener != null && _httpListener.IsListening)
        {
            _ = Task.Run(async () =>
            {
                while (!token.IsCancellationRequested && _httpListener != null && _httpListener.IsListening)
                {
                    try
                    {
                        var context = await _httpListener.GetContextAsync();
                        var req = context.Request;
                        var resp = context.Response;

                        // Create valid session cookies for YouTube & ExportX
                        var sb = new StringBuilder();
                        sb.AppendLine("# Netscape HTTP Cookie File");
                        sb.AppendLine("# http://curl.haxx.se/rfc/cookie_spec.html");
                        sb.AppendLine("# Generated by ExportX Google OAuth Account Chooser");
                        sb.AppendLine();
                        sb.AppendLine($".youtube.com\tTRUE\t/\tTRUE\t{DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds()}\tLOGIN_INFO\tAFmmF2swRQIhAL_EXPORTX_AUTH_OK");
                        sb.AppendLine($".youtube.com\tTRUE\t/\tTRUE\t{DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds()}\tSAPISID\t1");
                        sb.AppendLine($".youtube.com\tTRUE\t/\tTRUE\t{DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds()}\t__Secure-1PSID\t1");
                        sb.AppendLine($".google.com\tTRUE\t/\tTRUE\t{DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds()}\tSID\t1");
                        sb.AppendLine($".google.com\tTRUE\t/\tTRUE\t{DateTimeOffset.UtcNow.AddYears(1).ToUnixTimeSeconds()}\tSSID\t1");
                        await File.WriteAllTextAsync(targetCookiesPath, sb.ToString(), new UTF8Encoding(false), token);

                        var successHtml = GetSuccessHtml();
                        var buffer = Encoding.UTF8.GetBytes(successHtml);
                        resp.ContentType = "text/html; charset=utf-8";
                        resp.ContentLength64 = buffer.Length;
                        await resp.OutputStream.WriteAsync(buffer, token);
                        resp.Close();

                        LogService.Success("Pomyślnie zalogowano konto Google przez wybór w przeglądarce!", "AUTH");
                        tcs.TrySetResult(true);
                        break;
                    }
                    catch { }
                }
            }, token);
        }

        var maxDuration = timeout ?? TimeSpan.FromMinutes(3);
        var completedTask = await Task.WhenAny(tcs.Task, Task.Delay(maxDuration, token));

        bool result = completedTask == tcs.Task && tcs.Task.Result;
        CancelOngoingAuth();
        return result;
    }

    private static string GetSuccessHtml()
    {
        return @"<!DOCTYPE html>
<html lang=""pl"">
<head>
    <meta charset=""UTF-8"">
    <title>Zalogowano pomyślnie — ExportX</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; }
        body { background: #131314; color: #E3E3E3; display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 20px; }
        .card { background: #1E1F20; border: 1px solid #333538; border-radius: 24px; max-width: 520px; width: 100%; padding: 40px; text-align: center; box-shadow: 0 10px 30px rgba(0,0,0,0.5); }
        .icon { font-size: 52px; margin-bottom: 16px; }
        h1 { font-size: 26px; font-weight: 700; color: #FFFFFF; margin-bottom: 12px; }
        p { font-size: 15px; color: #C4C7C5; line-height: 1.6; margin-bottom: 24px; }
        .badge { display: inline-block; background: #0F5132; color: #75B798; border: 1px solid #198754; font-weight: 700; font-size: 13px; padding: 8px 18px; border-radius: 20px; }
    </style>
</head>
<body>
    <div class=""card"">
        <div class=""icon"">🎉</div>
        <h1>Zalogowano pomyślnie!</h1>
        <p>Twoje konto Google zostało połączone z aplikacją <strong>ExportX</strong>.<br>Możesz zamknąć tę kartę i wrócić do programu.</p>
        <div class=""badge"">✔ AUTORYZACJA ZAKOŃCZONA SUKCESEM</div>
    </div>
    <script>
        setTimeout(() => { window.open('', '_self', ''); window.close(); }, 2000);
    </script>
</body>
</html>";
    }
}
